### ISSUE TITLE
Clean up Request API for 1.9

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#588]
AHC2 targets Netty 4 and underlying code has been refactored a lot. It will take some time to get it stable.

Still, some APIs, like the Request one needs some clean up (deprecated methods that have already been removed on master) and some design choices have to be reconsidered because they lead to performance drop.

I see 1.9 as a pre AHC2, except that AHC2 targets Netty 4 and underlying code has been refactored a lot. So, let's clean things up now.
- [x] `getReqType` is deprecated in favor of `getMethod` => remove, see #590
- [x] `getLength` is deprecated in favor of `getContentLength` => remove, see #590
- [x] `getPerRequestConfig` and `PerRequestConfig` are deprecated => expose parameters directly on Request as it's done in AHC2, see #591
- [x] `getUrl`, `getRawUrl`, `getOriginalURI`, `getURI` and `getRawURI` are just some leaking implementation mess related to `isUseRawUrl` => have one single method, see #596
- [x] `isUseRawUrl` is confusing and not only applies on url but also on queryParams => rename to `isDisableUrlEncoding`, see #597
- [x] `java.net.URI` usage: expensive, restrictive (encoding issues) => replace with own class, see #589
- [x] `getParams`:
  - [x] confusing => rename into `getFormParams`, see #592
  - [x] no need for a `FluentStringsMap`, a `List<Param>` would suffice, see #595
- [x] `getQueryParams`:
  - [x] only used in OAuthSignatureCalculator => could be only computed on the fly from the query   String, see #598
  - [x] no need for a `FluentStringsMap`, a `List<Param>` would suffice, see #595
- [x] `isRedirectEnabled` and `isRedirectOverrideSet` should be merged into a single Boolean property, see #594

Regarding `FluentStringsMap`, there's maybe a usage for keeping it about for building requests, but I think we shouldn't use it in Request. It blocks extensibility.
