### ISSUE TITLE
Make AHC 1.9 and AHC2 code converge

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#638]
Code bases are very different, and that causes me huge maintenance efforts.
Also, I'm still not very confident with the Netty 4 provider in master, so it would be better to have both Netty 3 and Netty 4 support.
- [x] Drop JDK5 support and migrate to JDK6, see #639 
- [x] Reorganize Netty provider code to have a similar file structure, see #640 
- [x] Upgrade to AHC2 status, headers and parts API, see #641 
- [x] Refactor Response implementations duplicated code into ResponseBase, see #642 
- [x] Extract Handler logic out of the Netty provider, see #643
- [x] Drop 2nd level Part API, see #636
